project:
  type: website

website:
  title: "Ritwik Kinra"
  description: "PhD candidate in Economics at Georgetown University specializing in industrial organization and energy & environmental economics."
  navbar:
    right:
      - icon: envelope
        href: "mailto:rk1176@georgetown.edu"
      - icon: linkedin
        href: "https://www.linkedin.com/in/ritwikkinra"
      - icon: github
        href: "https://github.com/ritwikkinra"
      - icon: mortarboard-fill
        href: "https://scholar.google.com/citations?user=zKq7WnMAAAAJ"

format:
  html:
    theme: cosmo
